# Generated by Django 4.2.4 on 2023-09-04 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('views_number', models.PositiveIntegerField(default=0)),
                ('length_in_seconds', models.PositiveIntegerField(help_text='Duration of the video in seconds.')),
                ('cover_image', models.URLField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos_app.category')),
                ('users_watched', models.ManyToManyField(related_name='watched_videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
